export function loadContactPage() {
  const mainContent = document.getElementById('main-content');
  
  mainContent.innerHTML = `
    <section class="contact">
      <h1>Contact Information</h1>
      
      <div class="contact-content">
        <section class="contact-info">
          <h2>Get in Touch</h2>
          
          <div class="contact-item">
            <h3>Email</h3>
            <p><a href="mailto:your.email@example.com">your.email@example.com</a></p>
          </div>
          
          <div class="contact-item">
            <h3>Phone</h3>
            <p><a href="tel:+1234567890">+1 (234) 567-8900</a></p>
          </div>
          
          <div class="contact-item">
            <h3>Location</h3>
            <p>City, State, Country</p>
          </div>
          
          <div class="contact-item">
            <h3>Social Media</h3>
            <ul class="social-links">
              <li><a href="https://linkedin.com/in/yourprofile" target="_blank">LinkedIn</a></li>
            </ul>
          </div>
        </section>
        
        <section class="contact-form">
          <h2>Send me a Message</h2>
          <form id="contact-form">
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text" id="name" name="name" required>
            </div>
            
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" id="email" name="email" required>
            </div>
            
            <div class="form-group">
              <label for="subject">Subject</label>
              <input type="text" id="subject" name="subject" required>
            </div>
            
            <div class="form-group">
              <label for="message">Message</label>
              <textarea id="message" name="message" rows="5" required></textarea>
            </div>
            
            <button type="submit" class="btn btn-primary">Send Message</button>
          </form>
        </section>
      </div>
    </section>
  `;
  
  attachFormListener();
}

function attachFormListener() {
  const form = document.getElementById('contact-form');
  if (form) {
    form.addEventListener('submit', (e) => {
      e.preventDefault();
      handleFormSubmission(form);
    });
  }
}

function handleFormSubmission(form) {
  const formData = new FormData(form);
  const data = Object.fromEntries(formData);
  
  console.log('Form submitted with data:', data);
  
  alert('Thank you for your message! I will get back to you soon.');
  
  form.reset();
}
// This file was generated by Claude AI
